# statically link the MSVC C runtime so the .exe is self-contained
# (no VCRUNTIME140.dll / VC++ redistributable dependency on target machines)
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
